services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5440:5432'
    volumes:
      - tzDB:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    image: minio/minio
    container_name: aws
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_WEB_PORT}:${MINIO_WEB_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":${MINIO_WEB_PORT}"
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - internal

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - minio
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - ${PORTS}
    networks:
      - internal
volumes:
  tzDB:
  minio_data:
  redis_data:
    driver: local
networks:
  internal:
    name: tz_internal
    driver: bridge